# Generated by Django 3.0.3 on 2020-05-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.CharField(max_length=100)),
                ('prop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='pmMain.Prop_Name')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmMain.Room_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.CharField(max_length=200)),
                ('prop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pmMain.Prop_Name')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pmMain.Room_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.CharField(max_length=200)),
                ('prop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='pmMain.Prop_Name')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='pmMain.Room_Info')),
            ],
        ),
    ]
